esp32_serial_node:
  ros__parameters:
    # Hardware Settings
    wheel_base: 0.465             # (m) distance between wheels
    wheel_radius: 0.02            # (m) radius of wheels
    encoder_cpr: 700.0            # count per revolution, 
                                  # theoretical 13 PPR * 30 gear ratio * 4 encoders tick per revolution = 780
                                  # real case with minor error, use 700

    # Tune Command Velocity
    boost_vel: 1.1                # multiply velocity
    min_vel: 0.1                  # minimum velocity threshold

    # # Slip Ratio
    # base_slip_ratio: 0.057        # apply when moving in nearly straight line
    # param_n: 0.5                  # parameter to compensate speed difference between wheels

    # Serial Communication
    serial_port: "/dev/esp32"
    serial_baudrate: 115200
    serial_timeout: 1.0
    serial_timer: 0.08            # refresh rate for serial communication with ESP32 (12.4HZ, 0.08s)
                                  
    # Frame IDs
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    
    # Topic Names
    cmd_vel_topic: "/cmd_vel"
    odom_topic: "/odom"
    imu_topic: "/imu/data_raw"